// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs011_PeeBPg3srLxsjcC3CNY0xWWg-jo',
    appId: '1:459556189900:web:4131bc4637aa353be67469',
    messagingSenderId: '459556189900',
    projectId: 'capston-design-6d365',
    authDomain: 'capston-design-6d365.firebaseapp.com',
    storageBucket: 'capston-design-6d365.appspot.com',
    measurementId: 'G-G69XX5PBMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlha2mBwOkbokb_Emf32Ewq1YC658hijk',
    appId: '1:459556189900:android:81de665fece4fce3e67469',
    messagingSenderId: '459556189900',
    projectId: 'capston-design-6d365',
    storageBucket: 'capston-design-6d365.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe0seRLwJQZB6Y26ACuoAi1GhvbBbiET0',
    appId: '1:459556189900:ios:de74cdcc50b2feafe67469',
    messagingSenderId: '459556189900',
    projectId: 'capston-design-6d365',
    storageBucket: 'capston-design-6d365.appspot.com',
    iosClientId: '459556189900-0ge1fl4q0559ckr8ig804jb741uj0pc5.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstonApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs011_PeeBPg3srLxsjcC3CNY0xWWg-jo',
    appId: '1:459556189900:web:e5471bc334a466c7e67469',
    messagingSenderId: '459556189900',
    projectId: 'capston-design-6d365',
    authDomain: 'capston-design-6d365.firebaseapp.com',
    storageBucket: 'capston-design-6d365.appspot.com',
    measurementId: 'G-Z8N1C8RBRR',
  );
}
